<?php
/**
* The Evolution Framework
*
* WARNING: This file is part of the core Evolution Framework. DO NOT edit this file under any circumstances.
* Please do all modifications in the form of a child theme.
*
* This file loads all the scripts and styles
*
* @package Evolution\Functions\
* @author  Andreas Hecht
* @license GPL-2.0+
* @link    https://andreas-hecht.com/wordpress-themes/evolution-wordpress-framework/
*/


if ( !function_exists( 'evolution_scripts' ) ) :
/**
 * Enqueue scripts and styles.
 */
function evolution_scripts() { 

    wp_enqueue_style( 'evolution-style', get_stylesheet_uri() );
    
    wp_enqueue_style( 'fontawesome', get_theme_file_uri( '/css/font-awesome.min.css' ), array( 'evolution-style' ), '1.0.0' );

    wp_enqueue_script( 'evolution-navigation', get_template_directory_uri() . '/js/navigation.js', array(), '20160525', true );

    if ( is_singular() && comments_open() && get_option( 'thread_comments' ) ) {
        wp_enqueue_script( 'comment-reply' );
    }
}
add_action( 'wp_enqueue_scripts', 'evolution_scripts' );
endif;





if ( !function_exists( 'evolution_shortcodes_scripts' ) ) :
/**
 * Enqueue shortcodes scripts and stylesheet
 */
function evolution_shortcodes_scripts() {
    
    global $evolution;
    
    wp_register_style( 'evolution-shortcodes', get_template_directory_uri() . '/css/shortcodes.min.css' );

    $googlemaps_api = get_option( 'general-key' );

    wp_register_script( 'evolution-plugins', get_template_directory_uri() . '/js/plugins.js', array( 'jquery' ), EVOLUTION_THEME_VERSION, true );
    wp_register_script( 'evolution-init', get_template_directory_uri() . '/js/evolution.js', array( 'evolution-plugins' ), EVOLUTION_THEME_VERSION, true );
    wp_register_script('google-map', 'https://maps.googleapis.com/maps/api/js' . $googlemaps_api, null, null, true );
    wp_register_script( 'evolution-map', get_template_directory_uri() . '/js/map.js', null, EVOLUTION_THEME_VERSION, true );
    
    wp_enqueue_script( 'google-map' );
    wp_enqueue_script( 'evolution-map' );
    wp_enqueue_script( array( 'jquery', 'evolution-plugins', 'evolution-init' ) );
    wp_enqueue_style('evolution-shortcodes');
}
add_action( 'wp_enqueue_scripts', 'evolution_shortcodes_scripts' );
endif;





if ( !function_exists( 'evolution_admin_scripts' ) ) :
/**
 * Enqueue admin panel scripts and styles
 */
function evolution_admin_scripts() {

    wp_register_script( 'admin_evolution_js', get_template_directory_uri() . '/inc/includes/js/custom.js', false, '2.0.1', true );
    wp_enqueue_style( 'admin_evolution_css', get_template_directory_uri() . '/inc/includes/css/custom.css', false, EVOLUTION_THEME_VERSION );	

    $passed_data = array( 'expandedString' =>  __( '[-] Show less options', 'evolution-pro' ), 'closedString' => __( '[+] Show more options', 'evolution-pro' ) );

    wp_localize_script( 'admin_evolution_js', 'passed_data', $passed_data );

    wp_enqueue_script( array( 'jquery-ui-sortable', 'admin_evolution_js' ) );

}

add_action( 'admin_enqueue_scripts', 'evolution_admin_scripts', '999' );
endif;





if ( !function_exists( 'evolution_register_woostyles' ) ) :
/**
 * Register and load Custom Evolution WooCommerce Styles only on the right pages
 */
function evolution_woostyles() { 

    wp_register_style( 'evolution-woostyles', get_template_directory_uri() . '/inc/woocommerce/css/woo-styles.min.css' );

    if ( function_exists( 'is_woocommerce' ) ) :
    wp_enqueue_style( 'evolution-woostyles' ); 
    endif;
}
add_action( 'wp_enqueue_scripts', 'evolution_woostyles' );
endif;



/**
 * Adding the Button for the Shortcode Generator
 * @return Enable or disable the Shortcode Generator functions
 */
if ( ! function_exists( 'evolution_buttons' ) ) :

function evolution_buttons() {

    echo '<a data-effect="mfp-zoom-in" class="button button-primary evolution-shortcode-generator" href="#evolution-sc-generator"><span class="wp-shortcode-buttons-icon"></span> '. __('Evolution Shortcodes', 'evolution-pro' ).'</a>';  
}
endif; 
add_action( 'media_buttons', 'evolution_buttons', 100 );